# Databricks notebook source
# MAGIC %md
# MAGIC # Notebook 04 — Logical Data Modeling: Attributes, Types & Keys
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## What is a Logical Model?
# MAGIC
# MAGIC In Notebook 02, we built a **conceptual model**: boxes and lines, entities and relationships. No columns, no types — just the shape of the business domain.
# MAGIC
# MAGIC A **logical model** is the next level of detail. It takes the conceptual model and adds:
# MAGIC - Every **attribute** each entity tracks (the columns)
# MAGIC - **Data types** for each attribute (string, integer, date, decimal...)
# MAGIC - **Primary keys** (PKs) — the unique identifier for each row
# MAGIC - **Foreign keys** (FKs) — the links between tables
# MAGIC
# MAGIC Critically, a logical model is still **platform-independent**. We're not thinking about Delta Lake vs Parquet, or whether to partition by year. Those decisions come in the physical model (Notebook 06). Right now, we're modeling the data at a logical level that would work in any relational database.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Primary Keys vs Foreign Keys
# MAGIC
# MAGIC These two concepts are the backbone of every relational model:
# MAGIC
# MAGIC ### Primary Key (PK)
# MAGIC A primary key is a column (or combination of columns) that **uniquely identifies each row** in a table. Rules:
# MAGIC - Must be unique — no two rows can have the same PK value
# MAGIC - Cannot be NULL — every row must have an identity
# MAGIC - Should never change — if a customer changes their email, that's fine. If they change their `customer_id`, that breaks everything pointing to them.
# MAGIC
# MAGIC ### Foreign Key (FK)
# MAGIC A foreign key is a column in one table that **references the primary key of another table**. It enforces referential integrity — you can't have an order referencing a customer that doesn't exist.
# MAGIC
# MAGIC ### Surrogate Keys vs Natural Keys
# MAGIC
# MAGIC | Type | Definition | Example | Risk |
# MAGIC |---|---|---|---|
# MAGIC | **Natural key** | A real-world identifier from the source system | `customer_id = 1042` | Can change if source system changes. Can collide across systems. |
# MAGIC | **Surrogate key** | A synthetic key generated by the data warehouse | `customer_key = 'md5(1042)'` | No business meaning, but stable and controlled |
# MAGIC
# MAGIC In dimensional modeling we **always use surrogate keys** in the Gold layer. We keep the original `source_id` as a regular column for traceability, but the joins use our surrogate key. We'll explain why this matters in Notebook 09 when we discuss Slowly Changing Dimensions.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Our OLTP Logical Model
# MAGIC
# MAGIC This is how the data looks in its source (OLTP-style) form. These are the tables in `workspace.bronze.*`, designed for transaction recording — not for analytics.
# MAGIC
# MAGIC ```
# MAGIC ┌──────────────────────────────────────────────────────────────────┐
# MAGIC │                   OLTP LOGICAL MODEL                             │
# MAGIC └──────────────────────────────────────────────────────────────────┘
# MAGIC
# MAGIC ┌─────────────────────────┐     ┌─────────────────────────┐
# MAGIC │ CUSTOMER                │     │ LOCATION                │
# MAGIC │─────────────────────────│     │─────────────────────────│
# MAGIC │ PK customer_id   INT    │     │ PK location_id   INT    │
# MAGIC │    first_name    STRING │     │    city          STRING  │
# MAGIC │    last_name     STRING │     │    state         STRING  │
# MAGIC │    email         STRING │     │    region        STRING  │
# MAGIC │    phone         STRING │     │    country       STRING  │
# MAGIC │    address       STRING │     │    zip_code      STRING  │
# MAGIC │    city          STRING │     └─────────────────────────┘
# MAGIC │    state         STRING │
# MAGIC │    zip_code      STRING │
# MAGIC │    segment       STRING │
# MAGIC │    signup_date   DATE   │
# MAGIC └─────────────────────────┘
# MAGIC
# MAGIC ┌─────────────────────────┐     ┌─────────────────────────────────┐
# MAGIC │ PRODUCT                 │     │ ORDER                           │
# MAGIC │─────────────────────────│     │─────────────────────────────────│
# MAGIC │ PK product_id   INT     │     │ PK  order_id      INT           │
# MAGIC │    sku          STRING  │     │ FK  customer_id   INT → CUSTOMER│
# MAGIC │    product_name STRING  │     │ FK  product_id    INT → PRODUCT │
# MAGIC │    category     STRING  │     │ FK  location_id   INT → LOCATION│
# MAGIC │    subcategory  STRING  │     │     order_date    DATE          │
# MAGIC │    brand        STRING  │     │     quantity      INT           │
# MAGIC │    unit_price   DECIMAL │     │     unit_price    DECIMAL       │
# MAGIC │    cost_price   DECIMAL │     │     total_amount  DECIMAL       │
# MAGIC │    is_active    BOOLEAN │     │     channel       STRING        │
# MAGIC └─────────────────────────┘     │     status        STRING        │
# MAGIC                                 └─────────────────────────────────┘
# MAGIC                                              │
# MAGIC                                              │ (1:M)
# MAGIC                                              ▼
# MAGIC                                 ┌─────────────────────────────────┐
# MAGIC                                 │ RETURN                          │
# MAGIC                                 │─────────────────────────────────│
# MAGIC                                 │ PK  return_id     INT           │
# MAGIC                                 │ FK  order_id      INT → ORDER   │
# MAGIC                                 │ FK  customer_id   INT → CUSTOMER│
# MAGIC                                 │ FK  product_id    INT → PRODUCT │
# MAGIC                                 │     return_date   DATE          │
# MAGIC                                 │     return_amount DECIMAL       │
# MAGIC                                 │     reason        STRING        │
# MAGIC                                 └─────────────────────────────────┘
# MAGIC ```
# MAGIC
# MAGIC ### The Weak Entity: ORDER_LINE
# MAGIC
# MAGIC In a fully normalized OLTP model, we would also have an `ORDER_LINE` table — because one order can contain multiple products. Each line item would be a separate row.
# MAGIC
# MAGIC A **weak entity** is one that cannot be uniquely identified by its own attributes alone — it needs to borrow identity from a parent entity. ORDER_LINE has a composite PK: `(order_id, line_item_id)`. Without the `order_id`, `line_item_id = 1` is meaningless — it could belong to any order.
# MAGIC
# MAGIC In our simplified dataset, each order already contains a single product (one line item per order). So we don't need a separate ORDER_LINE table — the line item is embedded in the ORDER row. In production systems, you'd normalize this out.
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Translating from OLTP to Analytical (Dimensional) Logical Model
# MAGIC
# MAGIC This translation is the core skill of dimensional modeling. Every OLTP table is either:
# MAGIC 1. A **transaction entity** → becomes a **fact table** (stores what happened + FKs + measures)
# MAGIC 2. A **reference entity** → becomes a **dimension table** (stores context + attributes)
# MAGIC
# MAGIC Here are the rules for the translation:
# MAGIC
# MAGIC | OLTP pattern | Dimensional equivalent | Reason |
# MAGIC |---|---|---|
# MAGIC | Transaction entity (ORDER) | **Fact table** | Records events; holds measures (amount, qty) |
# MAGIC | Reference entity (CUSTOMER, PRODUCT) | **Dimension table** | Provides context; describes WHO, WHAT, WHERE |
# MAGIC | Date attributes scattered everywhere | **Date dimension** (new table!) | Centralizes all calendar logic |
# MAGIC | Natural keys (customer_id=1042) | **Surrogate keys** | Stable, controlled, source-system independent |
# MAGIC | M:M bridge table | **The fact table IS the bridge** | fact_orders connects customer ↔ product |
# MAGIC | Hierarchy in one table (category/subcategory) | **Flattened into one wide dimension** | Eliminates joins in analytical queries |
# MAGIC | Normalized sub-tables (2NF/3NF) | **Denormalized into parent** | Fewer joins = faster analytics = happier analysts |
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Our Analytical Logical Model
# MAGIC
# MAGIC After applying the translation rules, here is our complete **dimensional logical model** for `workspace.gold.*`:
# MAGIC
# MAGIC ```
# MAGIC ┌────────────────────────────────────────────────────────────────────────┐
# MAGIC │                ANALYTICAL LOGICAL MODEL (Star Schema)                  │
# MAGIC └────────────────────────────────────────────────────────────────────────┘
# MAGIC
# MAGIC ┌──────────────────────────┐   ┌──────────────────────────┐
# MAGIC │ dim_customer             │   │ dim_product              │
# MAGIC │──────────────────────────│   │──────────────────────────│
# MAGIC │ PK customer_key STRING   │   │ PK product_key   STRING  │
# MAGIC │    source_customer_id INT│   │    source_product_id INT │
# MAGIC │    full_name      STRING │   │    sku           STRING  │
# MAGIC │    email          STRING │   │    product_name  STRING  │
# MAGIC │    phone          STRING │   │    category      STRING  │
# MAGIC │    city           STRING │   │    subcategory   STRING  │
# MAGIC │    state          STRING │   │    brand         STRING  │
# MAGIC │    segment        STRING │   │    unit_price    DOUBLE  │
# MAGIC │    signup_date    DATE   │   └──────────────────────────┘
# MAGIC │    signup_year    INT    │
# MAGIC └──────────────────────────┘
# MAGIC
# MAGIC ┌──────────────────────────┐   ┌──────────────────────────────────────┐
# MAGIC │ dim_location             │   │ dim_date                             │
# MAGIC │──────────────────────────│   │──────────────────────────────────────│
# MAGIC │ PK location_key STRING   │   │ PK date_key        INT (YYYYMMDD)    │
# MAGIC │    source_location_id INT│   │    full_date        DATE             │
# MAGIC │    city          STRING  │   │    year             INT              │
# MAGIC │    state         STRING  │   │    quarter          INT              │
# MAGIC │    region        STRING  │   │    month            INT              │
# MAGIC │    country       STRING  │   │    month_name       STRING           │
# MAGIC │    zip_code      STRING  │   │    month_short      STRING           │
# MAGIC └──────────────────────────┘   │    week_of_year     INT              │
# MAGIC                                │    day_of_month     INT              │
# MAGIC                                │    day_of_week      INT              │
# MAGIC                                │    day_name         STRING           │
# MAGIC                                │    day_short        STRING           │
# MAGIC                                │    is_weekend       BOOLEAN          │
# MAGIC                                │    is_month_end     BOOLEAN          │
# MAGIC                                │    is_quarter_end   BOOLEAN          │
# MAGIC                                │    fiscal_year      INT              │
# MAGIC                                │    fiscal_quarter   INT              │
# MAGIC                                │    year_month       STRING           │
# MAGIC                                └──────────────────────────────────────┘
# MAGIC
# MAGIC ┌──────────────────────────────────────────────────────────────┐
# MAGIC │ fact_orders                                                   │
# MAGIC │──────────────────────────────────────────────────────────────│
# MAGIC │ PK order_key         STRING                                  │
# MAGIC │    source_order_id   INT                                     │
# MAGIC │ FK customer_key      STRING → dim_customer.customer_key      │
# MAGIC │ FK product_key       STRING → dim_product.product_key        │
# MAGIC │ FK location_key      STRING → dim_location.location_key      │
# MAGIC │ FK order_date_key    INT    → dim_date.date_key              │
# MAGIC │    quantity          INT                                     │
# MAGIC │    unit_price        DOUBLE                                  │
# MAGIC │    total_amount      DOUBLE                                  │
# MAGIC │    channel           STRING                                  │
# MAGIC │    order_year        INT                                     │
# MAGIC │    order_month       INT                                     │
# MAGIC └──────────────────────────────────────────────────────────────┘
# MAGIC
# MAGIC ┌──────────────────────────────────────────────────────────────┐
# MAGIC │ fact_returns                                                  │
# MAGIC │──────────────────────────────────────────────────────────────│
# MAGIC │ PK return_key        STRING                                  │
# MAGIC │    source_return_id  INT                                     │
# MAGIC │    source_order_id   INT                                     │
# MAGIC │ FK customer_key      STRING → dim_customer.customer_key      │
# MAGIC │ FK product_key       STRING → dim_product.product_key        │
# MAGIC │ FK return_date_key   INT    → dim_date.date_key              │
# MAGIC │    return_amount     DOUBLE                                  │
# MAGIC │    reason            STRING                                  │
# MAGIC │    return_year       INT                                     │
# MAGIC │    return_month      INT                                     │
# MAGIC └──────────────────────────────────────────────────────────────┘
# MAGIC ```
# MAGIC
# MAGIC ### What changed from OLTP to analytical?
# MAGIC
# MAGIC 1. **Natural keys replaced with surrogate keys**: `customer_id INT` → `customer_key STRING` (MD5 hash)
# MAGIC 2. **Date dimension added**: `order_date DATE` in the fact → `order_date_key INT` pointing to `dim_date`
# MAGIC 3. **Hierarchy flattened**: `category` and `subcategory` stay as separate columns in `dim_product` (no sub-table)
# MAGIC 4. **OLTP order table** → `fact_orders` (keeps measures, all FKs)
# MAGIC 5. **OLTP return table** → `fact_returns` (keeps measures, conformed FKs to same dims)
# MAGIC 6. **Full name denormalized**: `first_name + last_name` → single `full_name` column in `dim_customer`
# MAGIC
# MAGIC ---

# COMMAND ----------

# MAGIC %md
# MAGIC ## Seeing the Natural Keys We'll Replace
# MAGIC
# MAGIC Let's look at the natural keys that currently exist in our Bronze orders table. These are the `customer_id`, `product_id`, and `location_id` integers coming from the source system. We'll replace these with surrogate keys when building our Gold fact table.

# COMMAND ----------

# Show the natural keys in the orders table
print("Natural keys in workspace.bronze.orders:")
print("These integer IDs come from the source system.\n")
print("Problem: if the source system renumbers a customer (e.g., after a migration),")
print("all historical fact rows pointing to the old ID become orphaned.\n")

spark.sql("""
    SELECT
        order_id,
        customer_id,    -- natural key from source system
        product_id,     -- natural key from source system
        location_id,    -- natural key from source system
        order_date,
        total_amount
    FROM workspace.bronze.orders
    ORDER BY order_id
    LIMIT 10
""").show()

# COMMAND ----------

# Demonstrate the risk of natural keys:
# What happens if we count distinct customer_ids in orders vs actual customers?
print("Natural key integrity check: do all customer_ids in orders exist in customers?")
spark.sql("""
    SELECT
        COUNT(DISTINCT o.customer_id) AS distinct_customer_ids_in_orders,
        COUNT(DISTINCT c.customer_id) AS total_customers_in_master,
        COUNT(DISTINCT o.customer_id) - COUNT(DISTINCT c.customer_id) AS orphaned_ids
    FROM workspace.bronze.orders o
    LEFT JOIN workspace.bronze.customers c ON o.customer_id = c.customer_id
""").show()

# COMMAND ----------

# Show what the surrogate key WILL look like (preview of Gold layer design)
# We'll use MD5 of the source ID as a surrogate key
print("Preview: what the surrogate key approach looks like")
print("MD5 of the source customer_id becomes the stable, source-system-independent key\n")

spark.sql("""
    SELECT
        customer_id AS source_customer_id,
        md5(cast(customer_id AS STRING)) AS customer_key,
        first_name || ' ' || last_name AS full_name,
        email,
        segment
    FROM workspace.bronze.customers
    ORDER BY customer_id
    LIMIT 8
""").show(truncate=False)

# COMMAND ----------

# MAGIC %md
# MAGIC ## Summary
# MAGIC
# MAGIC In this notebook we:
# MAGIC
# MAGIC 1. Defined what a logical model is (conceptual + attributes, types, PKs, FKs)
# MAGIC 2. Distinguished primary keys from foreign keys, and natural keys from surrogate keys
# MAGIC 3. Walked through the complete OLTP logical model for our e-commerce schema
# MAGIC 4. Introduced the weak entity concept (ORDER_LINE with composite PK)
# MAGIC 5. Learned the rules for translating OLTP → analytical (dimensional) model
# MAGIC 6. Defined the complete analytical logical model: 4 dimension tables + 2 fact tables
# MAGIC 7. Demonstrated the natural keys we'll replace with surrogate keys
# MAGIC
# MAGIC **Next up — Notebook 05: Star Schema vs Snowflake Schema.** We'll compare the two most common dimensional schema patterns, run the same query on both, and make a final decision on which to use.
